import './dashboard.css';
import { Toaster } from '@/components/ui/toaster';
import { NextAuthProvider } from '@/contexts/auth';
import HeaderTwo from '@/components/HeaderTwo';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Toaster />
        <NextAuthProvider>
          <HeaderTwo />
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
